version: '3.8'
services:
  dnsmasq:
  build:
      context: .
      dockerfile: Dockerfile
    container_name: dnsmasq
    restart: always
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "192.168.10.100:53:53/udp"
      - "192.168.10.100:53:53/tcp"
    dns:
      - 8.8.8.8
      - 127.0.0.1
    cap_add:
      - NET_ADMIN
    volumes:
      - $PWD/dnsmasq.conf:/etc/dnsmasq.conf
      - /etc/hosts:/etc/hosts  #dockerホストの/etc/hostsを共有
